import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

// The sitemap is generated by src/pages/sitemap.xml.js (not @astrojs/sitemap),
// so it can filter out drafts and future-dated posts.
export default defineConfig({
  site: 'https://reubeningber.com',
  integrations: [tailwind()],
});
